---
# tasks file for ws-02-cyberark-postgress
- block:
  ###############################
    - block:
      
        - name: create file
          file:
            path: "{{role_path}}/files/postgres.json"
            state: touch

        - name: fetch user credentials from CyberArk API
          uri:
            url: "{{cyberark_postgress_url}}"
            validate_certs: yes
            return_content: yes
          register: postgres_output
          no_log: true

        - set_fact:
            pg_username: "{{(postgres_output.content|from_json).UserName}}"
            pg_password: "{{(postgres_output.content|from_json).Content}}"
          no_log: true

        - set_fact:
            # db_master_username: "{{pg_username}}"
            db_master_user_password: "{{pg_password}}"
          no_log: true

      rescue:

        - debug:
            msg: failed to retrieve postgres username and password from cyberark


  ###############################
  when: nocyberark is not defined