---
# tasks file for postgres-create

- block:

  - name: create subnet group
    rds_subnet_group:
      state: present
      name: "{{ db_subnet_group_name }}"
      description: "{{ db_subnet_group_name }}"
      region: "{{ aws_region }}"
      subnets: "{{subnets_used}}"


  # - name: create postgres database
  #   rds:
  #     command: create
  #     instance_name: "{{ db_instance_identifier }}"
  #     region: "{{ aws_region }}"
  #     db_name: "{{ db_name }}"
  #     db_engine: postgres
  #     size: "{{ db_allocated_storage }}"
  #     instance_type: "{{ db_instance_class }}"
  #     port: "{{ db_port }}"
  #     username: "{{ db_master_username }}"
  #     password: "{{ db_master_user_password }}"
  #     subnet: "{{ db_subnet_group_name }}"
  #     publicly_accessible: "{{db_is_public}}"
  #     vpc_security_groups: "{{db_security_group}}"
  #     multi_zone: yes
  #     wait: yes
  #     wait_timeout: 6000
  #     tags:
  #       Environment: "{{ deployment_env }}"
  #       Application: "{{ application_name }}"

  #   register: postgres_result

  - name: create mysql database
    rds:
      command: create
      instance_name: "{{ db_instance_identifier }}"
      region: "{{ aws_region }}"
      db_name: "{{ db_name }}"
      db_engine: MySQL
      size: "{{ db_allocated_storage }}"
      instance_type: "{{ db_instance_class }}"
      # port: "{{ db_port }}"
      username: "{{ db_master_username }}"
      password: "{{ db_master_user_password }}"
      subnet: "{{ db_subnet_group_name }}"
      publicly_accessible: "{{db_is_public}}"
      vpc_security_groups: "{{db_security_group}}"
      parameter_group: "md-labs-mysql-parameter-group"
      multi_zone: yes
      wait: yes
      wait_timeout: 6000
      tags:
        Environment: "{{ deployment_env }}"
        Application: "{{ application_name }}"

    register: postgres_result

  - name: capture the endpoint
    set_fact:
      db_endpoint: "{{ postgres_result.instance.endpoint }}"

  - debug:
      msg: "{{ postgres_result }}"

  - debug:
      msg: "{{db_endpoint}}"

  when: execute_postgres_create is defined and execute_postgres_create == 1