---
# tasks file for 00-vpc-create
- debug:
    msg: "{{ execute_vpc_create }}"
    
- block:
  - name: create a vpc with 6 subnets, in 3 az, public and private
    cloudformation:
      stack_name: "{{vpc_name}}"
      state: "present"
      region: "{{aws_region}}"
      template: "{{role_path}}/templates/vpc-3azs.yaml"
      template_parameters:
        ClassB: 68
      tags:
        Name: "ansible-cloudformation-vpc"
    register: vpc_result

  - name: show vpc stack result
    debug:
      msg: "{{ vpc_result.stack_outputs }}"

  - name: capture VpcId and subnets
    set_fact: 
      eks_public_subnets: "{{ vpc_result.stack_outputs.SubnetsPublic }}"
      eks_private_subnets: "{{ vpc_result.stack_outputs.SubnetsPrivate }}"
      VpcId: "{{vpc_result.stack_outputs.VPC}}"

  - name: verify eks_public_subnets
    debug:
      msg: "{{eks_public_subnets}}"

  - name: verify eks_private_subnets
    debug:
      msg: "{{eks_private_subnets}}"

  - name: verify VpcId
    debug:
      msg: "{{VpcId}}"
  
  - name: save VPC info to a file
    # local_action: 
    copy: 
      content: "{{ vpc_result.stack_outputs | to_nice_json }}" 
      dest: "{{ playbook_dir }}/environments/{{ deployment_env_short }}/vpc_info.json"      


  when: execute_vpc_create is defined and execute_vpc_create == 1
      