---
# tasks file for postgres-data

- block:

  - name: create tables in the database
    postgresql_query:
      db: "{{db_name}}"
      login_host: "{{db_endpoint}}"
      login_user: "{{db_master_username}}"
      login_password: "{{db_master_user_password}}"
      port: "{{db_port}}"
      path_to_script: "{{ role_path }}/files/create_tables.sql"
    
    register: data_result_01

  - debug:
      msg: "{{ data_result_01 }}"

  - name: populate wthr_metars_rpt with data
    postgresql_query:
      db: "{{db_name}}"
      login_host: "{{db_endpoint}}"
      login_user: "{{db_master_username}}"
      login_password: "{{db_master_user_password}}"
      port: "{{db_port}}"
      path_to_script: "{{ role_path }}/files/insert_data.sql"
    
    register: data_result_02

  - debug:
      msg: "{{ data_result_02 }}"

  when: (nodataload is not defined) or (nodataload is defined and nodataload == 1)