---
  # #######################################################
  # global variables
  deployment_env: aia

  business_unit: md-labs
  application_name: hudi-demo

  aws_account: 156021229203
  aws_region: us-east-1

  path_to_source: "{{ playbook_dir }}/../source"
  path_to_build: "{{ playbook_dir }}/../build"

  bucket_artifacts: md-labs-hudi-demo-artifacts-bucket

  # #######################################################
  # security variables

  # #######################################################
  # vpc variables
  vpc_name: "{{ business_unit }}-{{ application_name }}-vpc"
  sg_name: "{{ business_unit }}-{{ application_name }}-sg"
  public_subnets: ""
  private_subnets: ""

  # where many ports will be open to, can be your home public ip
  sg_cidr: "98.199.0.0/16"

  # #######################################################
  # rds variables
  ec2_keypair: "md-labs-key-pair"

  # #######################################################
  # emr variables

  # #######################################################
  # dms variables

  # #######################################################
  # glue variables
  glue_db_name: "{{ business_unit }}_{{ application_name }}_glue_db"


  # #######################################################
  # flow control variables
  nocyberark: 1
  execute_vpc_create: 1



