---
# Vars for dl-non-prod environment

default_region: us-east-1
prefix_bu: md-labs
prefix_app: hudi-demo


ec2_keypair: "md-labs-key-pair"

# Default VPC values, all will be populated with real values
default_vpc_id: "vpc-0536d6e718c0f8ba4"
default_vpc_private_subnet_a: "subnet-01747a9730d177c4b"
default_vpc_private_subnet_b: "subnet-02bb448f61df34f9f"
default_vpc_private_subnet_c: "subnet-05ee6041a2513a6a6"

default_vpc_public_subnet_a: "subnet-01747a9730d177c4b"
default_vpc_public_subnet_b: "subnet-02bb448f61df34f9f"
default_vpc_public_subnet_c: "subnet-05ee6041a2513a6a6"
