---
#####################################################################################################
#                                                                                                   #
# Usage:                                                                                            #
#                                                                                                   #
# ansible-playbook retract.yaml -e "deployment_env=aia"
# ansible-playbook retract.yaml -e "deployment_env=non-prod"
# ansible-playbook retract.yaml -e "deployment_env=prod"
#                                                                                                   #
# ansible-playbook retract.yaml -e "deployment_env=aia nocyberark=1"
# ansible-playbook retract.yaml -e "deployment_env=non-prod nocyberark=1"
# ansible-playbook retract.yaml -e "deployment_env=prod nocyberark=1"
#                                                                                                   #
#####################################################################################################

- hosts: localhost
  remote_user: root

  vars:
    # this will be usually specified in command line params
    - deployment_env: aia      # must be overwritten with an inline variable. eg: ... -e "deployment_env=non-prod"

  tasks:
    - include_vars: "./environments/{{ deployment_env }}/main.yml"               # global variables
    - include_vars: "./environments/common_vars.yaml"                            # common vars same in all environments
######################################################################################################
    - block:
#######################################################################################################

      - name: get account id from aws cli caller identity
        shell: "aws sts get-caller-identity --query Account --output text"
        register: account_id_shell_response

      - set_fact:
          account_id: '{{account_id_shell_response.stdout}}'
          bucket_data: "md-labs-hudi-demo-data-bucket-{{ account_id }}"


      - name: retract solution cloudformation
        amazon.aws.cloudformation:
          stack_name: "{{ business_unit }}-{{ application_name }}-main-solution-stack"
          state: absent
          region: "{{ aws_region }}"
        ignore_errors: yes


      - name: delete data bucket
        amazon.aws.aws_s3:
          bucket: "{{ bucket_data }}"
          mode: delete
        ignore_errors: yes


#######################################################################################################
      always:
#######################################################################################################
        - name: clean up
          include_role:
            name: ws----cleanup-aws      # not executed if nocyberark is defined
#######################################################################################################